server:
  port: 9000
spring:
  application:
    name: eureka_server
#配置eureka server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: true #是否从eureka中获取注册信息
    service-url: #配置暴露给eureka client的请求地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #改为其它Eureka Server的地址和端口


